### ISSUE TITLE
Dashboard acting up

### ISSUE THREAD

**Issue by unlstorm** [ThermoMan/Thermostat-Tracking#27]
I'm getting errors on the dashboard page (and have been for a while).  My log files are getting -rw-r--r-- permissions with root/root as the user/group.  My logs directory has 777 permissions.  

![errors_on_dashboard](https://f.cloud.github.com/assets/2549596/1197282/ae5f7754-24d1-11e3-9045-0e0ed21fe990.png)

**Comment by ThermoMan** [comment]
I'm moving to an in home server running Ubuntu and it has a whole slew of issues with user/group file and directory ownership and permissions.

In the mean time the code has changed a ton.  New version will be posted soon-ish.  (This new version also has a large DB restructure that I'll try to write instructions for, but some steps will be manual)
