### ISSUE TITLE
Database changes to optimize and improve

### ISSUE THREAD

**Issue by unlstorm** [ThermoMan/Thermostat-Tracking#36]
Ok... Starting this as a new thread spurring from the discussion around creating a new setpoints table.

I am working on making the setpoints table with an id field that is related to the thermostats.id field.  As I was doing this I noticed I had type issues so I decided to change the thermostats.id and related table fields to use tinyint's that are unsigned.  This should give the flexibility to handle up to 255 thermostats and keep some efficiency to the database.  Do you guys agree this should be an acceptable change to make as we start to make relationships between the tables with the 'id' column?

**Comment by ThermoMan** [comment]
Setpoint got postponed once I did my first curl statement and realized "Oh hell, there is ZERO authentication needed to futz with the stat".
I left this as a "wontfix" for a long time.  It's deferred until after the next update that assumes LAN only, no WAN access because of #66

**Comment by ThermoMan** [comment]
This is tied to v2.  V3 will have the same setup but is structured differently.
