### ISSUE TITLE
Display customization

### ISSUE THREAD

**Issue by Lerrissirrel** [ThermoMan/Thermostat-Tracking#38]
I've been looking for something more to contribute here.  I'm happy to take suggestions based on a "todo" list you might have (and would do such a thing first).  But one I thought about adding was customizations to the display.  Like custom colors, line types, and such.  Any thoughts?

**Comment by ThermoMan** [comment]
Here's a rough outline of a dashboard idea I've been working on.

![dashboard wip](https://user-images.githubusercontent.com/1949042/41757213-3a544cc4-75a6-11e8-801c-ac97b479afe4.png)

**Comment by ThermoMan** [comment]
This issue is so tied to v2 that it's stuck.  V3 will need new display customizations, but those will be all new issues.
