### ISSUE TITLE
heat/fan/cool gradients could possibly draw off the chart

### ISSUE THREAD

**Issue by unlstorm** [ThermoMan/Thermostat-Tracking#54]
It it because of the $sqlThree query. I think we can avoid that query all together if the current day does not fall into the range of the currently plotted data. Is it easy to see if "today" falls between the range of $start_date and $end_date and only if it does, perform the sqlThree query?

**Comment by ThermoMan** [comment]
I am replacing pChart with a client side JavaScript charting utility.
Before I moved the code off the hosted server I was getting tasks killed because I was using too much of the CPU and as a consequence, no more charts.
New code posting soon-ish.
