### ISSUE TITLE
Filtrete 3M-50 Issue or Furnace Issue

### ISSUE THREAD

**Issue by unlstorm** [ThermoMan/Thermostat-Tracking#58]
Went on vacation last week and furnace went on the fritz while in-laws stayed here.  I tried to adjust the radio thermostat settings from my mobile phone >1400 miles away without success.  Called HVAC technician out today and he found a few interesting things.  He said he found a possible loose connection on my furnace servo for the gas valve.  He also said my 3M-50 thermostat wasn't sending out enough voltage to enable heat.  I then went upstairs and reset the thermostat (reset button near the NORM/HP switch).  He said the voltage looked good after I did this.  I'm still confused by this situation and what was the real root cause (i.e. thermostat or loose wire near the servo).  Anyway, I have heat again and probably a nice HVAC technician bill coming soon.  

Figured I would share this information in case anyone on here sees a similar issue with this kind of thermostat (or in-laws/tenants that don't like your indoor climate control settings... :-)).  Might be worthwhile trying to reset the thermostat yourself before calling a technician.  Perhaps I was changing the thermostat settings over the internet near or at the same time my in-laws were doing something with the actual device.  I'm leaning more towards the thermostat as being the root cause of my condition since the wires in the furnace wouldn't have been touched while I was on vacation.

**Comment by ThermoMan** [comment]
I created a feature request wiki page and added this
https://github.com/ThermoMan/Thermostat-Tracking/wiki/Requests
