### ISSUE TITLE
issues with KLogger.php

### ISSUE THREAD

**Issue by hans109h** [ThermoMan/Thermostat-Tracking#65]
I'm unsure that I've installed KLogger.php correctly.  I keep getting the following:
```

PHP Fatal error:  Uncaught Error: Call to undefined method KLogger::instance() in /var/www/Thermostat-Tracking/common.php:24
Stack trace:
#0 /var/www/Thermostat-Tracking/thermo.php(2): require_once()
#1 {main}
  thrown in /var/www/Thermostat-Tracking/common.php on line 24

```
any suggestions?

**Comment by ThermoMan** [comment]
I have been using a larger tree for some common library files that I use across several projects.  Look in config.php at the very bottom line
add_include_path( $rootDir . '../common/php/' );

This is a relative reference from the thermo2 directory to the common directory where I have shared libraries.  If you use a similar thing you can change the path there.
Or if you put the KLogger library in the lib directory you can change the include statement in common.php to something like.
require_once( 'lib/KLogger.php' );

**Comment by ThermoMan** [comment]
Did this solve your problem?  Please re-open if it did not.
